### PR TITLE
ci: Remove OpenCL support (easy)

### PR DESCRIPTION
**Pull request by huitseeker**
- Removed 'test-opencl' job from the Rust workflow file (.github/workflows/rust.yml).
- Rust test suite is no longer being tested with OpenCL enabled, but continues to be tested with CUDA enabled through the 'test-cuda' job.

### CODE REVIEW

**Review by samuelburnham — COMMENTED** [review]
Makes sense to me, but I think we should also:
- Document lack of explicit support in the Readme
- Switch `gbench`'s default feature from `opencl` to `cuda` if possible
- Consider sunsetting the `opencl` feature entirely

**Comment by huitseeker** [comment]
@porcuquine opinions on the above?

**Comment by vmx** [comment]
Is the only about removing OpenCL from CI, or is the plan to also remove it from the code base. I'm asking as the Filecoin proofs rely on Neptune and I'd prefer not to fork it.

Also I'd really like if OpenCL would still be running. What is the reason to remove it. Maintenance burden? Cost? Something else? I'd be happy to take care of the OpenCL part if needed (again to prevent a fork).

**Comment by huitseeker** [comment]
@vmx The question was more about lack of interest in that feature. As there is indeed interest, we're happy to keep it running.

**Comment by vmx** [comment]
@huitseeker k, cool. As I said, if you run into any issues related to OpenCL, feel free to ping me (or anyone else from the Filecoin Proofs team).

**Pull request closed without merging**
